CREATE PUBLIC SYNONYM USUARIO FOR EQDAW02.USUARIO;
CREATE PUBLIC SYNONYM ASISTENTE FOR EQDAW02.ASISTENTE;
CREATE PUBLIC SYNONYM CALENDARIO FOR EQDAW02.CALENDARIO;
CREATE PUBLIC SYNONYM DUENO FOR EQDAW02.DUENO;
CREATE PUBLIC SYNONYM ENTRENADOR FOR EQDAW02.ENTRENADOR;
CREATE PUBLIC SYNONYM EQUIPO FOR EQDAW02.EQUIPO;
CREATE PUBLIC SYNONYM FICHERO FOR EQDAW02.FICHERO;
CREATE PUBLIC SYNONYM JORNADA FOR EQDAW02.JORNADA;
CREATE PUBLIC SYNONYM JUGADOR FOR EQDAW02.JUGADOR;
CREATE PUBLIC SYNONYM PARTIDO FOR EQDAW02.PARTIDO;
CREATE PUBLIC SYNONYM RESULTADO FOR EQDAW02.RESULTADO;
CREATE PUBLIC SYNONYM ROL FOR EQDAW02.ROL;


select *
from user_synonyms;
